# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorControl', models.IntegerField(max_length=50)),
                ('visitorVariation', models.IntegerField(max_length=50)),
                ('conversionControl', models.IntegerField(max_length=50)),
                ('conversionVariation', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
