# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='conversionControl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='input',
            name='conversionVariation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='input',
            name='visitorControl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='input',
            name='visitorVariation',
            field=models.IntegerField(default=0),
        ),
    ]
